String04 프로젝트 [메소드를 찾을 수 없음]오류 해결(list.jsp) 및 삭제버튼 진행 도중 오류 발생하여 확인 중
오류코드 :  ### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: 테이블 또는
뷰가 존재하지 않습니다

; bad SQL grammar []; nested exception is
java.sql.SQLSyntaxErrorException: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
]을(를) 발생시켰습니다.
Error : 942, Position : 12, Sql = DELETE FROM border_file
		WHERE num = :1 , OriginalSql = DELETE FROM border_file
		WHERE num = ?, Error Msg = ORA-00942: 테이블 또는 뷰가 존재하지 않습니다